include dracula.conf
include ${KITTY_OS}.conf

font_family               JetBrainsMono Nerd Font Mono
enable_audio_bell         no
hide_window_decorations   yes

# add 1px to the left
window_padding_width 0 0 0 1

enabled_layouts grid, vertical 
map shift+enter send_text all \x1b[13;2u
