font_size 10.0

map cmd+c         send_text all \x03
map ctrl+c        copy_to_clipboard
map ctrl+v        paste_from_clipboard

map ctrl+s        new_window_with_cwd
map ctrl+shift+s  new_window
map ctrl+w        close_window_with_confirmation
map ctrl+l        next_window
map ctrl+h        previous_window

map ctrl+t        new_tab_with_cwd
map ctrl+shift+t  new_tab
map ctrl+tab      next_tab
