font_size 18.0

map ctrl+c        send_text all \x03
map cmd+c         copy_to_clipboard
map cmd+v         paste_from_clipboard

map cmd+s         new_window_with_cwd
map cmd+shift+s   new_window
map cmd+w         close_window_with_confirmation
map cmd+l         next_window
map cmd+h         previous_window

map cmd+t         new_tab_with_cwd
map cmd+shift+t   new_tab
map cmd+tab       next_tab
